import 'package:flutter/material.dart';
import 'package:git_search/src/presenter/style/app_colors.dart';

final lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.primary.light,
  onPrimary: AppColors.onPrimary.light,
  primaryContainer: AppColors.primaryContainer.light,
  onPrimaryContainer: AppColors.onPrimaryContainer.light,
  secondary: AppColors.secondary.light,
  onSecondary: AppColors.onSecondary.light,
  secondaryContainer: AppColors.secondaryContainer.light,
  onSecondaryContainer: AppColors.onSecondaryContainer.light,
  tertiary: AppColors.tertiary.light,
  onTertiary: AppColors.onTertiary.light,
  tertiaryContainer: AppColors.tertiaryContainer.light,
  onTertiaryContainer: AppColors.onTertiaryContainer.light,
  error: AppColors.error.light,
  errorContainer: AppColors.errorContainer.light,
  onError: AppColors.onError.light,
  onErrorContainer: AppColors.onErrorContainer.light,
  background: AppColors.background.light,
  onBackground: AppColors.onBackground.light,
  surface: AppColors.surface.light,
  onSurface: AppColors.onSurface.light,
  surfaceVariant: AppColors.surfaceVariant.light,
  onSurfaceVariant: AppColors.onSurfaceVariant.light,
  outline: AppColors.outline.light,
  onInverseSurface: AppColors.onInverseSurface.light,
  inverseSurface: AppColors.inverseSurface.light,
  inversePrimary: AppColors.inversePrimary.light,
  shadow: AppColors.shadow.light,
  surfaceTint: AppColors.surfaceTint.light,
);

final darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.primary.dark,
  onPrimary: AppColors.onPrimary.dark,
  primaryContainer: AppColors.primaryContainer.dark,
  onPrimaryContainer: AppColors.onPrimaryContainer.dark,
  secondary: AppColors.secondary.dark,
  onSecondary: AppColors.onSecondary.dark,
  secondaryContainer: AppColors.secondaryContainer.dark,
  onSecondaryContainer: AppColors.onSecondaryContainer.dark,
  tertiary: AppColors.tertiary.dark,
  onTertiary: AppColors.onTertiary.dark,
  tertiaryContainer: AppColors.tertiaryContainer.dark,
  onTertiaryContainer: AppColors.onTertiaryContainer.dark,
  error: AppColors.error.dark,
  errorContainer: AppColors.errorContainer.dark,
  onError: AppColors.onError.dark,
  onErrorContainer: AppColors.onErrorContainer.dark,
  background: AppColors.background.dark,
  onBackground: AppColors.onBackground.dark,
  surface: AppColors.surface.dark,
  onSurface: AppColors.onSurface.dark,
  surfaceVariant: AppColors.surfaceVariant.dark,
  onSurfaceVariant: AppColors.onSurfaceVariant.dark,
  outline: AppColors.outline.dark,
  onInverseSurface: AppColors.onInverseSurface.dark,
  inverseSurface: AppColors.inverseSurface.dark,
  inversePrimary: AppColors.inversePrimary.dark,
  shadow: AppColors.shadow.dark,
  surfaceTint: AppColors.surfaceTint.dark,
);
